import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Job Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <nav className="bg-purple-300 p-4 rounded-sm">
            <div className="flex gap-24 font-bold text-lg">
              <Link className="nav-link" href="/">Home</Link>
              <Link className="nav-link" href="/about">About</Link>
              <Link className="nav-link" href="/contact">Contact</Link>
            </div>
          </nav>

          {/* Page Content */}
          <main>{children}</main>
      </body>
    </html>
  );
}
